### ISSUE TITLE
[css] `border-width` follows spec, but isn't the same computed value in FF and Chrome

### ISSUE THREAD

**Issue by usadson** [usadson/retina#33]
## Reproduction
Take the following example from [ACID 1](https://www.w3.org/Style/CSS/Test/CSS1/current/test5526c.htm)
```css
html {
    font: 10px/1 Verdana, sans-serif;
    background-color: blue;
    color: white;
}

li {
    display: inline;
    /* i.e., suppress marker */
    color: black;
    height: 9em;
    width: 5em;
    margin: 0;
    border: .5em solid black;
    padding: 1em;
    float: left;
    background-color: #FC0;
}
```

## Explanation
Here, the computed value of `font-size` is `10px`. This is the same as in other browsers.

Setting a `border-width` of `.5em` would “obviously” compute to `10 * 0.5 = 5px` right? No. Firefox and Chrome both compute the value to `4.8px`:
![image](https://github.com/usadson/retina/assets/58562158/63fbe3fc-837e-4203-8e44-cd964f55d760)
![image](https://github.com/usadson/retina/assets/58562158/e28f74f6-c504-4092-889d-33edf00c11df)

The weirdest part is, when rendering the given borders, both browser engines render a rect of 6 pixels wide!
